### ISSUE TITLE
[feature request] alternative or custom key for completion

### ISSUE THREAD

**Issue by zcysxy** [Pierrad/obsidian-github-copilot#11]
Thank you so much for this plugin! Copilot is finally here for Obsidian!

Like Vim, `Tab` for completion here is tricky in Obsidian, as many plugins register this key. For example, when [LaTeX Suite](https://github.com/artisticat1/obsidian-latex-suite) is enabled, the Tab key won't work for GitHub Copilot. Is it possible to use keys other than `Tab`? It would be great if the user can configure it.

**Comment by Pierrad** [comment]
Hi @zcysxy, 

Thanks for using the plugin. I'm currently working on a way to add keybinding (see `feature/11` branch).

In the meantime, I've added a fix to use the `Tab` key with the LaTeX Suite plugin or when writing a list. Please see #12 for details. 

You can update to 1.0.1 to retrieve this fix.

**Comment by Pierrad** [comment]
@zcysxy I've update the plugin to add keybinding customization. It is available in the `v1.0.2`.

You can see example in the following screencast : 

https://github.com/Pierrad/obsidian-github-copilot/assets/32339081/d03ccaa2-cd63-4ff3-9e3d-431167825dbf

Please tell me if this fill your needs!

**Comment by zcysxy** [comment]
Yeah this is exactly what I want. Works like a charm! Thank you @Pierrad 🎉
