### ISSUE TITLE
Conflict with Latex Suite Plugin

### ISSUE THREAD

**Issue by ProudBenzene** [Pierrad/obsidian-github-copilot#12]
**Describe the bug**

Open LaTeX Suite with Copilot plugin at the same time, and when you press the Tab key again it will not auto-complete but indent.

**To Reproduce**
1. Installing the LaTeX Suite plug-in
2. Press Tab while displaying Copilot's complement again

This plugin works FANTASTIC and I hope you can fix this!

**Comment by Pierrad** [comment]
Hi @ProudBenzene, thanks for using the plugin!

I fixed the issue, you can update the plugin to version `1.0.1`. 

Here's a screencast of using this plugin with the LaTeX Suite plugin activated at the same time after the update : 

https://github.com/Pierrad/obsidian-github-copilot/assets/32339081/37c43c80-5011-4f3d-a495-cd7b470247ed


Please tell me if this solves your issue!

**Comment by ProudBenzene** [comment]
I didn't encounter any problems in testing the new version, thanks for the prompt fix!🥳
