### ISSUE TITLE
Additional configuration: Delay before generating, Only inside codeblocks, Hotkey to trigger generation

### ISSUE THREAD

**Issue by sammcj** [Pierrad/obsidian-github-copilot#14]
**Is your feature request related to a problem? Please describe.**

Great plugin, I'd suggest a few additional configuration options:

- Configurable delay before generating (e.g. only generate if paused for 1s)
- Only run inside codeblocks (so your normal note content doesn't try to auto-complete, but code inside code blocks does)
- Option to only complete on hotkey (e.g. cmd+shift+/ to trigger a generation)

**Comment by Pierrad** [comment]
Hi @sammcj,

Thanks for using the plugin!

I've updated the plugin to add your features requests. It's available in the `v1.0.5`.

Let me know if it fit your needs!

**Comment by sammcj** [comment]
Yes! That’s awesome, thank you!
