### ISSUE TITLE
No Copilot Suggestions

### ISSUE THREAD

**Issue by gwerneckp** [Pierrad/obsidian-github-copilot#17]
**Describe the bug**
No Copilot Suggestions are appearing

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable Copilot
2. Start typing

**Expected behaviour**
Suggestions should appear.

**Obsidian and environment (please complete the following information):**
 - OS: Arch Linux
 - Obsidian version: 1.5.12
 - Plugin version: 1.0.3

**Additional context**
On the logs, I get:
```
stdout: Content-Length: 92

{"jsonrpc":"2.0","id":3,"result":{"completions":[],"cancellationReason":"RequestCancelled"}}
```

every time I type a word.

(related to #15, I did not rename `package.json` back.)

**Comment by Pierrad** [comment]
@gwerneckp It seems that this is a problem related to the copilot agent (see https://github.com/copilot-emacs/copilot.el/issues/181 for related issue).

I will see what I can do.

**Comment by Pierrad** [comment]
Hi @gwerneckp,

On the `v1.0.5` update, the copilot core has changed a lot, so maybe it will fix your issue with not getting completions?
