### ISSUE TITLE
On Windows 'Program Files'  node path causes copilot fail

### ISSUE THREAD

**Issue by serrnovik** [Pierrad/obsidian-github-copilot#20]
On windows node is located at: `C:\Program Files\nodejs\node.exe`

Providing this path to `Node Binary Path` results in successful test path test

However turning on plugin will result in error in dev console:
```
plugin:github-copilot:27023 stderr: 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

Changing path to `"C:\Program Files\nodejs\node.exe"` (*putting qoutes inside the field*) will make plugin work however path test will fail.

**Comment by DMeurer** [comment]
Same bug with same results.

With `C:\Program Files\nodejs\node.exe` the path test button will recognize the file, but when enableing debug mode, you can see it wont find it.

With `"C:\Program Files\nodejs\node.exe"` the patch check will fail, but it will start to work.

Thank you for this awesome Plugin, I cant use a local LLM with my potato laptop.

**Comment by Pierrad** [comment]
Hi @serrnovik  @DMeurer,

Thanks for using the plugin!

I've updated the plugin, you can download the `v1.0.5` and you should be able to have a space in the node path without the need to add double quotes around.
I've tested the fix with a windows VM so it should be okay but let me know if it's okay on your side!

**Comment by serrnovik** [comment]
> I've updated the plugin, you can download the `v1.0.5` and you should be able to have a space in the node path without the need to add double quotes around. I've tested the fix with a windows VM so it should be okay but let me know if it's okay on your side!

I confirm. It is working withoug qoutes now. 

Great plugin in fact! Having VSCode copilot experience in obsidian is just great! Merci.
