### ISSUE TITLE
Next suggestion

### ISSUE THREAD

**Issue by kublaios** [Pierrad/obsidian-github-copilot#21]
**Is your feature request related to a problem? Please describe.**
When writing prose, Copilot usually suggests more than one completion. Currently, I am getting only the first one, potentially missing out on other variants.

**Describe the solution you'd like**
A hotkey to see the next suggestion. Ideally, with being able to cycle between suggestions (one-way or two ways).

Last but not least, thank you for creating this plugin! The onboarding was super-smooth and it helps a lot with staying focused during writing. 🙌

**Comment by Pierrad** [comment]
Hi @kublaios, thanks for using the plugin!

In `v1.0.7`, if there is multiple suggestions provided by copilot, you will see a small box indicating that you are currently seeing the 1/X suggestions. You can cycle between those suggestion using the new hotkey available in the settings. See my example below : 

https://github.com/Pierrad/obsidian-github-copilot/assets/32339081/999f204b-eedc-4583-9f7c-6abd802a7c0c

Let me know if it fit your needs!

**Comment by kublaios** [comment]
Thanks, @Pierrad - it is perfect! I'm closing this one, thanks for the quick resolution 💯
