### ISSUE TITLE
Feature Request: Add Option to Exclude Specific Files and Folders from Suggestions

### ISSUE THREAD

**Issue by andretcarpizo** [Pierrad/obsidian-github-copilot#23]
It would be nice to have an option to set excluded files and folders where we don't want to see suggestions.

For instance, a similar feature already exists in the files and links menu.

![excluded files](https://github.com/Pierrad/obsidian-github-copilot/assets/69943379/bfb7b6a7-da84-4e4f-8b25-c26e9a4c20f4)
![excluded modal](https://github.com/Pierrad/obsidian-github-copilot/assets/69943379/46fa7745-9d5e-4324-8139-94bc9e4e44fc)

**Comment by Pierrad** [comment]
Hi @andretcarpizo,

Thanks for using the plugin!

In the `v1.0.8`, you can now select some folders and files to exclude, here's an example : 

https://github.com/Pierrad/obsidian-github-copilot/assets/32339081/885ec10c-d966-4a94-9fca-fc82a5ed22cd

Please tell me if it fits your need!
