### ISSUE TITLE
Issued with Lists

### ISSUE THREAD

**Issue by Canna71** [Pierrad/obsidian-github-copilot#24]
First of all, this plugin is wonderful and is what I was looking for since I often reverted to editing markdown files in VSCode for the lack of Github Copilot integration in other tools.

One issue I have is that the Tab expansion is problematic in numbered or bulleted lists. Maybe something could be done?

**Comment by Pierrad** [comment]
Hi @Canna71, thanks for using the plugin!

Can you be a bit more specific on what you mean by "problematic in numbered or bulleted lists"? Can you provide a screencast and maybe what behavior you would like to see at the end?

Also, on which version of the plugin are you?

**Comment by Canna71** [comment]
Sure, let's say that Copilot is suggesting you a list of items:
![image](https://github.com/Pierrad/obsidian-github-copilot/assets/5303303/ed304c13-0eb5-4db6-a419-3a107d577474)
Now when you press Tab in this situation, the editor wins and intents the line instead of accepting the suggested text:
![image](https://github.com/Pierrad/obsidian-github-copilot/assets/5303303/3d7e3c85-d86b-4d10-9efc-6b5b6bdfc8af)

Changing the Accept shortcut to something else works, but I would prefer it to be Tab (like VSCode). I wonder if this is possible with CodeMirror, but if there is an active suggestion than the Tab should be handled by your plugin, while revert to the default behaviour otherwise.

**Comment by Pierrad** [comment]
@Canna71 Oh I see, it's weird, this issue should have been resolved a few versions ago. 

As you can see from my screencast, I do not have the issue with recent version (`v1.0.6`). Do you have an older version of the plugin? Or maybe a plugin that is overriding the default behavior of the `Tab` key?

https://github.com/Pierrad/obsidian-github-copilot/assets/32339081/a7da6a9e-9e88-4cfc-899f-5b855cedcace

**Comment by Pierrad** [comment]
Ah you said that you can change the Accept shortcut, so you have at least the version with the fix normally :/

**Comment by Canna71** [comment]
@Pierrad thank you for taking the time to record the video!
I forgot to add that I am using version 1.0.6, but after your comment I investigated, and it turned out that it is the Outliner plugin's fault (specifically the "Enhance Tab key" feature).

Sorry for wasting your time

**Comment by Pierrad** [comment]
No problem! Glad to see that it is solved!
