### ISSUE TITLE
Exclude the path from Obsidian Sync

### ISSUE THREAD

**Issue by Michaelpalacce** [Pierrad/obsidian-github-copilot#25]
Currently, if you are using obsidian sync on multiple devices, syncing the path will result in issues, as the path will be different on each device.

Proposition is to store the path in a separate json file that will not be picked up by sync

**Comment by LuCa-0** [comment]
I'm not using obsidian sync but google drive and i'm running into the same problem when switching between windows and macos. This would help a lot!

**Comment by Pierrad** [comment]
Hi @Michaelpalacce & @LuCa-0,

Thanks for using the plugin!

I added a settings to enable saving the nodePath to a `device_data.json`. The nodePath will be saved in both data json files but if the setting is enabled, it takes the nodePath from the `device_data.json` file. If this file is not sync between device it should allow you to have different configuration between devices. 

![Capture d’écran 2024-06-23 à 10 37 22](https://github.com/Pierrad/obsidian-github-copilot/assets/32339081/1c66b606-b6fa-4d40-a0a7-b50f81e83e68)

Can you tell me if it works on your side?

**Comment by LuCa-0** [comment]
Sorry for the delay! It does indeed work perfectly. Thanks for the update!

**Comment by Michaelpalacce** [comment]
Sorry I didn't see the update either! Perfect! Thank you lots

**Comment by Zhaoyilunnn** [comment]
> I'm not using obsidian sync but google drive and i'm running into the same problem when switching between windows and macos. This would help a lot!

Hi @LuCa-0 , could you elaborate on how do you manage to exclude the `device_data.json` file from google drive? Thanks in advance!
