### ISSUE TITLE
Autosuggestion will follow my 光标

### ISSUE THREAD

**Issue by eightHundreds** [Pierrad/obsidian-github-copilot#26]
**Describe the bug**
![Export-1718762938125](https://github.com/Pierrad/obsidian-github-copilot/assets/18695431/b6d28fe8-d9a8-47ac-b992-f605fe237e42)

**To Reproduce**

**Expected behavior**
I hope the suggestion will disappear after the cursor position changes

**Screenshots**
If applicable, add screenshots to help explain your problem with console logs if possible.

**Obsidian and environment (please complete the following information):**
 - OS: 14.5 (23F79)
 - Obsidian version: 1.6.0
 - Plugin version [e.g. 1.0.0] : 1.0.7

**Additional context**

**Comment by Pierrad** [comment]
Hi @eightHundreds,

Thanks for using the plugin!

I fixed this issue in the `v1.0.8` as you can see in the following example : 


https://github.com/Pierrad/obsidian-github-copilot/assets/32339081/28c1fa9b-cdc5-4f09-a850-a2942f9cc567
