### ISSUE TITLE
A hotkey setting for enabling/disabling copilot.

### ISSUE THREAD

**Issue by LiamSwayne** [Pierrad/obsidian-github-copilot#28]
When I'm using Obsidian there are distinct scenarios when I always want copilot suggestions and never want copilot suggestions. For example: I want copilot off when writing creatively and on when drafting email templates and doing other mundane tasks.

The current features for enabling and disabling with folders are very good but when switching between tasks very quickly it would be more convenient to just hit a hotkey to disable/enable copilot suggestions.

Edit: Forgot to add the context that I'm using Vim so the status bar isn't super convenient to use.

**Comment by Pierrad** [comment]
Hi @LiamSwayne,

Thanks for using the plugin!

I've added a new hotkey to enable / disable copilot, please tell me if it fits your need!

**Comment by LiamSwayne** [comment]
Just downloaded the update and it works super well! Thanks so much for adding this feature!
