### ISSUE TITLE
Suggestions don't disappear when navigating with hjkl in vim mode

### ISSUE THREAD

**Issue by i-am-the-slime** [Pierrad/obsidian-github-copilot#35]
**Describe the bug**
Suggestions don't disappear when navigating with hjkl in vim mode

**To Reproduce**
1. Activate the VIM keybindings
2. Get a suggestion at the end of a line, then hit escape and move the cursor anywhere
3. The stale suggestion moves along with the cursor wherever it goes

**Expected behavior**
The suggestion should be dismissed when moving away from the original position and potentially refresh at the new position

**Screenshots**
<img width="696" alt="Bildschirmfoto 2024-07-30 um 11 44 29" src="https://github.com/user-attachments/assets/a360f2e7-1cc4-481a-87f7-5aaa4b2f2ef7">

<img width="417" alt="Bildschirmfoto 2024-07-30 um 11 44 38" src="https://github.com/user-attachments/assets/264aea6d-31d8-4c64-8f37-4fe7be0bdabe">

**Obsidian and environment (please complete the following information):**
 - OS: macOS
 - Obsidian version: 1.6.7
 - Plugin version:  1.0.6 

**Additional context**
Great plugin, thanks!

**Comment by Pierrad** [comment]
Hi @i-am-the-slime, thanks for using the plugin!

I see that you're using the `v1.0.6` of the plugin, you should upgrade to the last version, in `v1.0.8` I fix this bug that was also happening when not using the vim mode.

**Comment by i-am-the-slime** [comment]
Merci beaucoup, Pierrad. Maintenant, c'est impeccable.
