### ISSUE TITLE
Extension doesn't work on Flatpak installation

### ISSUE THREAD

**Issue by timo-x30xe** [Pierrad/obsidian-github-copilot#6]
Hello i went through the manual installation and the settings/ the button to enable and disable at the bottom appeared as expected.
I added my node path "/usr/bin/node" but im still not getting any completion suggestions.

when opening the Console it shows an error being thrown at startup (Uncaught Error: write EPIPE)
[obsidian.md-1715152018123.log](https://github.com/Pierrad/obsidian-github-copilot/files/15245124/obsidian.md-1715152018123.log)

I also never received the ready to use notice stated in step 4 of the installation.

Any guidance on what to try from here?

**Comment by Pierrad** [comment]
Hi @timo-x30xe, thanks for your interest!

From your log, it seems that the node process is not running as expected when we try to communicate with it. 
This possibly comes from a problem with your node path or your node version. Can you give more information about your node version?

If you installed the plugin by cloning the project, can you enabled the debugging mode (turn the setDebug to true l.30 in the main.ts file), it will give use more detail about the child process crash.

**Comment by Pierrad** [comment]
@timo-x30xe I've updated the code to add a "Test the path" button near the node path input in the plugin settings. 
It will check for you if the node path is accessible, executable and if the node version is correct. 

You can get this update by pulling the last commit or downloading the last released files in the Release 1.0.0.

**Comment by timo-x30xe** [comment]
Hi, thanks for the update. I am using just the release file instead of building it from source.

Using the "Test the Path"-Button throws an error but nothing pops up in the Obsidian log (see Screenshot)
![image](https://github.com/Pierrad/obsidian-github-copilot/assets/47715636/6c947152-6838-45a0-aeef-55b7cfcd0d00)

The path is the same that is being returned by "which node" and the version is 20.12.0
![image](https://github.com/Pierrad/obsidian-github-copilot/assets/47715636/b1ecc10e-7925-4d04-869c-38fe60c92361)

There also now appears to be a "Copilot has stopped" notification popping up when enabling the extension.

**Comment by timo-x30xe** [comment]
I just realised it might have to do with Obsidian being a flatpak installation for me.
so i tried adding "/var/run/host/" in front of my path which gives me a different error
![image](https://github.com/Pierrad/obsidian-github-copilot/assets/47715636/1aa8e226-25d6-4886-ba9b-8add32897274)

**Comment by Pierrad** [comment]
@timo-x30xe I've implemented the sign-in process in case you need it. You can download the files from the release 1.0.0. 

If you're not signed in, a popup will appear with instruction to follow.

Don't hesitate to tell me if it works for you or not

**Comment by timo-x30xe** [comment]
@Pierrad Thank you! The Method you described worked flawlessly. Didn't expect you to go through that trouble reproducing it with a VM for such a niche issue. I also used the Sign-in Process as it popped up and it worked without any issues
Thanks for the fast response and the great work on the plugin!
